
name: Scheduled All Projects Trigger

on:
  workflow_dispatch:

jobs:
  trigger:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: verify if this PR meets all the checks
        id: prCheck
        uses: arup-group/action-check-pr-state@main
        with:
          requiredReviews: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Branch
        if: steps.prCheck.outputs.pullRequestToRerun
        uses: Hatzelencio/merge-branch@v0.0.1
        with:
          head: ${{ steps.prCheck.outputs.headRef }}
          base: ${{ steps.prCheck.outputs.baseRef }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Allow time for merge to happen (10 seconds)
        run: sleep 10
          
      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.approved.outputs.approvedReviews == 1 }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: /azp run All Projects
